<a href="https://colab.research.google.com/github/Roshini-br/DS-MINOR-MAY/blob/main/Image_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Cosidered Data in the form of images

In [1]:
!pip install ipython-autotime
%load_ext autotime 

time: 2.3 ms (started: 2021-06-30 04:52:21 +00:00)


In [2]:
!pip install bing_image_downloader

time: 3.14 s (started: 2021-06-30 04:52:53 +00:00)


In [3]:
!mkdir images

time: 112 ms (started: 2021-06-30 04:53:23 +00:00)


In [4]:
from bing_image_downloader import downloader
downloader.download("Pretty Red Roses",limit=25,output_dir='images',adult_filter_off=True)

[%] Downloading Images to /content/images/Pretty Red Roses


[!!]Indexing page: 1

[%] Indexed 25 Images on Page 1.


[%] Downloading Image #1 from https://i.pinimg.com/originals/58/d2/45/58d2452c06dc34306a8aa31585f5092c.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://i.pinimg.com/originals/23/2a/d8/232ad8f75d95f829662ef2082ce7442d.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://i.pinimg.com/originals/d2/c6/32/d2c632e73789985ea0d8203c154e95d4.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://i.pinimg.com/originals/3b/3b/15/3b3b152ac8b643a5bc26c0773646f8ff.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://i.pinimg.com/originals/8f/32/40/8f324001dbfc21c1e6186241f18dd9ef.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://i.pinimg.com/originals/4f/25/08/4f2508f998ec187ee62e6c27ecc2ed2c.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://s-media-cache-ak0.pinimg.com/736x/28/10/79/281079455c97639dba724

In [5]:
from bing_image_downloader import downloader
downloader.download("Guava Fruit",limit=25,output_dir='images',adult_filter_off=True)

[%] Downloading Images to /content/images/Guava Fruit


[!!]Indexing page: 1

[%] Indexed 25 Images on Page 1.


[%] Downloading Image #1 from https://live.staticflickr.com/47/126627494_992392300d_b.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://heddysue.com/wp-content/uploads/2020/09/Acca-sellowiana-Feijoa-Pineapple-guava-fruit.jpg
[%] File Downloaded !

[%] Downloading Image #3 from http://1.bp.blogspot.com/_8ONSfnCAMGw/Stg69I5a3AI/AAAAAAAAANU/8-4NfbO_9bk/s400/seedless_guava_2.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://i.ebayimg.com/images/i/150759058595-0-1/s-l1000.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://i.ebayimg.com/images/g/YegAAOSw6~VZvN3w/s-l400.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://i.ebayimg.com/images/g/DLQAAOSw3v5YqcqW/s-l400.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://i.ebayimg.com/images/g/LQwAAOxyBLxRG002/s-l300.jpg
[%] File Downloaded !

[%] Downloading Image 

In [6]:
from bing_image_downloader import downloader
downloader.download("Dogs",limit=25,output_dir='images',adult_filter_off=True)

[%] Downloading Images to /content/images/Dogs


[!!]Indexing page: 1

[%] Indexed 25 Images on Page 1.


[%] Downloading Image #1 from http://trueworkingdogs.com/wp-content/uploads/20170312_105719.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://i.pinimg.com/originals/ef/14/32/ef1432cf6e4e96b0aa5dbb2662db797e.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://trueworkingdogs.com/wp-content/uploads/20180422_151229.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://i.pinimg.com/originals/8b/7a/09/8b7a09e00936e33bfd441506b6592e45.jpg
[%] File Downloaded !

[%] Downloading Image #5 from http://trueworkingdogs.com/wp-content/uploads/20170312_105910.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://img1.grunge.com/img/gallery/false-facts-about-dogs-you-always-thought-were-true/intro.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://img4.grunge.com/img/uploads/2016/12/false-facts-about-dogs-you-always-thought-were-true

In [7]:
#preprocessing

import os
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
from skimage.transform import resize

target = []
images = []
flat_data = []

DATADIR ="/content/images"
CATEGORIES = ['Pretty Red Roses','Guava Fruit','Dogs']

for category in CATEGORIES:
  class_num = CATEGORIES.index(category)
  # print(class_num)
  path = os.path.join(DATADIR,category)
  # print(path)
  for img in os.listdir(path):
    img_array = imread(os.path.join(path,img))
    #print(img_array.shape)
    #plt.imshow(img_array)
    img_resized = resize(img_array,(150,150,3))
    flat_data.append(img_resized.flatten())
    images.append(img_resized)
    target.append(class_num)


flat_data =  np.array(flat_data)
target = np.array(target)
images = np.array(images)

time: 21.2 s (started: 2021-06-30 05:04:45 +00:00)


In [9]:
flat_data[0]

array([0., 0., 0., ..., 0., 0., 0.])

time: 4.62 ms (started: 2021-06-30 05:06:13 +00:00)


In [10]:
len(flat_data[0])

67500

time: 3.27 ms (started: 2021-06-30 05:06:27 +00:00)


In [11]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2])

time: 5.92 ms (started: 2021-06-30 05:06:46 +00:00)


In [12]:
unique,count = np.unique(target,return_counts=True)
plt.bar(CATEGORIES,count)

<BarContainer object of 3 artists>

time: 153 ms (started: 2021-06-30 05:07:10 +00:00)


In [13]:
#splitting the data into training and testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(flat_data,target,test_size=0.3,random_state=109)

time: 183 ms (started: 2021-06-30 05:07:34 +00:00)


In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param_grid = [
              {'C':[1,10,100,1000],'kernel':['linear']},
              {'C':[1,10,100,1000],'gamma':[0.001,0.0001],'kernel':['rbf']},
]

svc = svm.SVC(probability=True)
clf = GridSearchCV(svc,param_grid)
clf.fit(x_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

time: 1min 19s (started: 2021-06-30 05:08:59 +00:00)


In [15]:
y_pred = clf.predict(x_test)
y_pred

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 2, 0, 0, 1, 2, 1, 2, 1, 2, 2, 1, 1, 0,
       0])

time: 142 ms (started: 2021-06-30 05:11:14 +00:00)


In [16]:
y_test

array([1, 2, 0, 1, 0, 1, 1, 0, 1, 0, 2, 0, 2, 2, 1, 2, 1, 2, 0, 1, 0, 0,
       0])

time: 3.45 ms (started: 2021-06-30 05:11:40 +00:00)


In [17]:
from sklearn.metrics import accuracy_score,confusion_matrix

time: 2.11 ms (started: 2021-06-30 05:12:01 +00:00)


In [18]:
accuracy_score(y_pred,y_test)

0.6956521739130435

time: 5.09 ms (started: 2021-06-30 05:12:19 +00:00)


In [19]:
confusion_matrix(y_pred,y_test)

array([[5, 0, 2],
       [2, 8, 1],
       [2, 0, 3]])

time: 5.59 ms (started: 2021-06-30 05:12:37 +00:00)


In [20]:
# save the model using pickle library
import pickle
pickle.dump(clf,open('img_model.p','wb'))

time: 33.5 ms (started: 2021-06-30 05:13:13 +00:00)


In [21]:
model = pickle.load(open('img_model.p','rb'))

time: 16.1 ms (started: 2021-06-30 05:13:35 +00:00)


In [22]:
#Testing the new Image
flat_data = []
url = input('Enter your URL')
img = imread(url)
img_resized = resize(img,(150,150,3))
flat_data.append(img_resized.flatten())
flat_data = np.array(flat_data)
print(img.shape)
plt.imshow(img_resized)
y_out = model.predict(flat_data)
y_out = CATEGORIES[y_out[0]]
print(f' PREDICTED OUTPUT: {y_out}')

Enter your URLhttps://post.medicalnewstoday.com/wp-content/uploads/sites/3/2020/02/322868_1100-800x825.jpg
(825, 800, 3)
 PREDICTED OUTPUT: Dogs


time: 47.3 s (started: 2021-06-30 05:14:15 +00:00)


In [23]:
#Testing the new Image
flat_data = []
url = input('Enter your URL')
img = imread(url)
img_resized = resize(img,(150,150,3))
flat_data.append(img_resized.flatten())
flat_data = np.array(flat_data)
print(img.shape)
plt.imshow(img_resized)
y_out = model.predict(flat_data)
y_out = CATEGORIES[y_out[0]]
print(f' PREDICTED OUTPUT: {y_out}')

Enter your URLhttps://5.imimg.com/data5/GD/DL/MY-44116104/guava-fruit-500x500.jpg
(500, 500, 3)
 PREDICTED OUTPUT: Guava Fruit


time: 36.2 s (started: 2021-06-30 05:16:14 +00:00)
